### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by pvulakh** [rayoowoo/AssembledFaces#2]
Really awesome work on this! A few changes to make:

### misc:
- [x] add timestamps to the tables that don't have them :)
- [x] remove `photos` table since you'll be using AWS
- [x] move `workplaces`, `educations`, `locations` tables into the bonus section on the bottom. For now, these will be represented by strings in the `users` table
- [ ] `post_likes`/`comment_likes` are a bonus so we can discuss this further if you do implement these, but as food for thought it could be worth making a polymorphic association (`likes` table will have a column of `likeable_type` (string of 'comment' or 'post') and `likeable_id` (foreign key that points to a row in the `comments` table or `posts` table))

### `users`:
- [x] change foreign keys to bonus tables (workplaces, educations, locations) into strings containing their respective names
- [x] add `current_city` and `hometown` columns
- [x] add a `not null` constraint to `birth_date`

### `posts`:
- `author_id` vs `user_id` - if this is to account for posting on a different user's timeline, how are posts on a user's own timeline catalogued? Would `author_id == user_id` in that case? 
- [x] if the `text` column refers to whether this is a text post, or a `photo`/`video` post, what happens if the author wanted to provide a caption as well as a url? Let's remove this column and account for `photo`/`video` content via AWS - that way all posts can still have a text body, and posts that have an attached photo or video will still have a field that can serve as the caption

### `friend_requests`/`friendships`:
- [x] consolidate these into one `friendships` table and add a `status` column that will account for whether the friendship is pending or approved. If a user chooses to ignore a friend request, the row representing this friend request will be deleted from the db to allow for re-requesting while preserving the unique index on `[requester_id, requested_friend_id]`. Let me know if you have questions on this!

**Comment by rayoowoo** [comment]
To answer the question about `author_id` versus `user_id`, yes, `author_id` refers to the user that makes the post, and `user_id` refers to the user on whose timeline the post lives. So if the user posts on his or her own timeline, `author_id === user_id`.
